name: CI/CD

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov

      - name: Run unit tests with coverage
        run: |
          . venv/bin/activate
          export PYTHONPATH=$(pwd)
          pytest --cov=. --cov-report=xml:coverage.xml || echo "Tests failed"

      - name: Install Newman (Postman CLI)
        run: npm install -g newman

      - name: Run Postman API tests
        run: newman run postman/ApiGeraNomes.json --reporters cli || echo "Postman tests failed"