name: CI/CD

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  # Job para rodar os testes unitários
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          . venv/bin/activate
          pytest --maxfail=1 --disable-warnings -v --cov=. --cov-report=xml
  # Job para análise no SonarCloud após os testes passarem
  sonarcloud:
    runs-on: ubuntu-latest
    needs: test  # Garante que os testes sejam executados antes de realizar a análise
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install SonarScanner
        run: |
          curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
          unzip sonar-scanner.zip
          mv sonar-scanner-5.0.1.3006-linux sonar-scanner
          echo "$GITHUB_WORKSPACE/sonar-scanner/bin" >> $GITHUB_PATH

      - name: Run SonarCloud analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner \
            -Dsonar.organization=<YOUR_ORG> \
            -Dsonar.projectKey=<YOUR_PROJECT_KEY> \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=$SONAR_TOKEN \
            -Dsonar.python.coverage.reportPaths=coverage.xml

  # Job para deploy (se necessário)
  deploy:
    runs-on: ubuntu-latest
    needs: sonarcloud  # Garante que o deploy só ocorra após a análise no SonarCloud
    steps:
      - name: Deploy to Render
        run: |
          # Adicione aqui o seu comando de deploy, por exemplo:
          # render deploy --service <YOUR_SERVICE_NAME> --branch master