name: CI/CD

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m venv venv
          venv/bin/pip install --upgrade pip
          venv/bin/pip install -r requirements.txt
          venv/bin/pip install pytest pytest-cov

      - name: Run tests with coverage
        run: |
          export PYTHONPATH=$(pwd)
          venv/bin/pytest --cov=. --cov-report=xml:coverage.xml || echo "Tests failed"

      - name: Upload coverage report (opcional)
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage.xml