jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov

      - name: Run unit tests with coverage
        run: |
          . venv/bin/activate
          export PYTHONPATH=$(pwd)
          pytest --cov=. --cov-report=xml:coverage.xml || echo "Tests failed"

      - name: Start API
        run: |
          . venv/bin/activate
          uvicorn main:app --host 127.0.0.1 --port 8000 --reload &
          sleep 3  # Aguarda 3 segundos antes de prosseguir
        env:
          PYTHONPATH: ${{ github.workspace }}

      - name: Install Newman (Postman CLI)
        run: npm install -g newman

      - name: Run Postman API tests
        run: newman run postman/ApiGeraNomes.json --no-cache --reporters cli,json --reporter-json-export postman-report.json